### ISSUE TITLE
Container

### ISSUE THREAD

**Issue by 5ch3m45** [MuhammadHammamNurFaizi/Traknus#3]
Untuk containering content. pake class .container atau .container-fluid ya.
coba tambahin class itu disamping class .body ini
![class body](https://i.ibb.co/qmgC0hw/Screen-Shot-2023-09-15-at-19-18-10.png)

**Comment by MuhammadHammamNurFaizi** [comment]
Oke..

Pada tanggal Jum, 15 Sep 2023 19.19, Maulana Ichwan Anshory <
***@***.***> menulis:

**Comment by 5ch3m45** [comment]
![](https://i.ibb.co/RP8x6rS/Screen-Shot-2023-09-20-at-23-48-50.png)
di halaman kedatanganunit.html. div .table-responsive masukin ke div .container-fluid aja mam
![](https://i.ibb.co/x7C0YPg/Screen-Shot-2023-09-20-at-23-55-28.png)
sama, ini di halaman monitoringrosemuadata.html & planmutasisemua.html masukin ke .container-fluid juga ya

![](https://i.ibb.co/9tbWXct/Screen-Shot-2023-09-20-at-23-52-51.png)
di halaman monitoring ro, ada .container-fluid di dalam .container-fluid, hapus aja class .container fluid yang bawah yes.
di planmutasisaat.html juga

**Comment by MuhammadHammamNurFaizi** [comment]
done update bang

**Comment by 5ch3m45** [comment]
sippp
