### ISSUE TITLE
Table Action Button

### ISSUE THREAD

**Issue by 5ch3m45** [MuhammadHammamNurFaizi/Traknus#4]
![](https://i.ibb.co/gJZTHzF/Screen-Shot-2023-09-15-at-19-20-27.png)

linknya coba di dalem button. pake .btn .btn-sm .btn-light biar bisa kecil

**Comment by 5ch3m45** [comment]
![](https://i.ibb.co/8j3Drjs/Screen-Shot-2023-09-21-at-00-09-43.png)
buat ningkatin user xperience aja.
button Edit, textnya jadiin biru
button Hapus, textnya jadiin merah ya mam

**Comment by MuhammadHammamNurFaizi** [comment]
done update bang

**Comment by 5ch3m45** [comment]
udah ok
